# Generated by Django 5.2.5 on 2025-08-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessToken',
            fields=[
                ('user_access_token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_access_token', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('user_access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='api.userdata')),
            ],
        ),
    ]
